### ISSUE TITLE
great prompt issue with fish shell

### ISSUE THREAD

**Issue by larntz** [IsaccBarker/Greatness#12]
My default shell is fish and when I run `great prompt` I am getting the error below. 

```
🦔 You are now in a great child shell. Type `exit` to return to your great previous shell!
/bin/fish: option requires an argument -- 'f'
```

Apparently fish doesn't like the `-f` flag, and it's not actually opening a new shell due to the error. 

Thought I'd let you know.

**Comment by IsaccBarker** [comment]
I can't work on this issue now, but I'll start work tomorrow. Thanks for your issue!

In the mean time you can just cd into `~/.greatness/pack/git` and run your commands there.

**Comment by larntz** [comment]
Understood... no rush. Being able to cd into the directory is plenty good for me!

**Comment by IsaccBarker** [comment]
Just got the changes into the mainline, and I gotta say.... Wow, is fish colourful!

**Comment by IsaccBarker** [comment]
Note that its not in the crates.io repo yet, that'll happen later once I get more features done.
