### ISSUE TITLE
How to add directory?

### ISSUE THREAD

**Issue by noyez** [IsaccBarker/Greatness#17]
I have a ~/.zsh/  directory with a bunch of other files and directories. I can't seem to add the directory into great. How can i do this? I tried doing `great add .zsh` and `great add .zsh/*` the former didn't work, and the latter only worked for files (not directories) and only the first level of files. 

```
mba :: ~  » great add .zsh .zshrc
🦔 The file .zsh doesn't exist, and thus cannot become great (be added). Skipping....
```

**Comment by IsaccBarker** [comment]
Sorry for the late response, I've been away :\. At this point you cannot, but I'll add this to a feature board. For now, run something like
`great add $(find .zsh)`
